quarkus:
  application:
    name: esthesis-dfl-mqtt-client
  container-image:
    group: esthesisiot
    name: esthesis-dfl-mqtt-client
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
#  native:
#    additional-build-args: --initialize-at-run-time=io.quarkus.runner.ApplicationImpl\\,io.quarkus.runtime.generated.Config
#camel:
#  remove:
#    headers:
#      pattern: "X-Esthesis-KafkaTopic"
