server:
  log_level: warn
  disable: false
  http_listen_port: 2234
  grpc_listen_port: 0
clients:
  - url: http://grafana-loki-distributor.esthesis:3100/loki/api/v1/push
positions:
  filename: /run/promtail/positions.yaml
scrape_configs:
  - job_name: gelf
    gelf:
      listen_address: "0.0.0.0:12201"
      use_incoming_timestamp: true
    pipeline_stages:
      - json:
          expressions:
            severity: _Severity
            platform: _platform
            module: _module
            type: _type
            service: _service
            host: host
      - labels:
          severity:
          platform:
          module:
          type:
          service:
          host:
