####################################################################################################
# esthesis device agent image builder, using 'busybox' as base image.
#
# This image produces an image that contains the esthesis-core-device agent, its dependencies, as
# well as a BusyBox shell. Using this image, you can get a shell into a running containers, as well
# as executuing commands using the pseudo-terminal of esthesis CORE.
#
# The image is built in two stages:
# 1. Build stage: The esthesis-core-device agent is built using the golang:1.21.3-bookworm image.
# 2. Runtime stage: The esthesis-core-device agent is copied to a new image based on 'busybox'.
####################################################################################################

# Build stage.
FROM golang:1.21.3-bookworm AS build
ARG LDFLAGS=""
ENV CGO_ENABLED=0

WORKDIR /app
COPY go/. .
RUN go mod download
RUN go build -ldflags "$LDFLAGS" -o /native/esthesis-core-device cmd/main.go
RUN mkdir /nonexistent

# Runtime stage.
FROM busybox:1.36.1
LABEL maintainer="esthesis@eurodyn.com"

RUN cat /etc/passwd
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --chown=65534:65534 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65534:65534 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65534:65534 --from=build /native/esthesis-core-device /app/esthesis-core-device
COPY --chown=65534:65534 --from=build /nonexistent /nonexistent

EXPOSE 8080 1883
USER nobody
ENTRYPOINT ["/app/esthesis-core-device"]
