quarkus:
  application:
    name: esthesis-srv-tag
  container-image:
    group: esthesisiot
    name: esthesis-srv-tag
  mongodb:
    connection-string: mongodb://mongodb:27017
    database: esthesis
    credentials:
      username: esthesis
      password: esthesis
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    handler:
      gelf:
        enabled: true
        host: 192.168.21.12
        port: 12201
  opentelemetry:
    enabled: true

mp:
  jwt:
    verify:
      publickey:
        location: "http://esthesis-keycloak/realms/esthesis/protocol/openid-connect/certs"

