quarkus:
  application:
    name: esthesis-core-srv-dataflow
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-dataflow
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  rest-client:
    DockerClient:
      url: https://registry.hub.docker.com
      scope: Singleton
    SettingsResource:
      url: http://esthesis-core-srv-settings-service:8080
      scope: Singleton
    TagResource:
      url: http://esthesis-core-srv-tag-service:8080
      scope: Singleton
    KubernetesResource:
      url: http://esthesis-core-srv-kubernetes-service:8080
      scope: Singleton
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
