quarkus:
  application:
    name: esthesis-dfl-control-reply-updater
  container-image:
    group: esthesisiot
    name: esthesis-dfl-control-reply-updater
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-20.20c{1.}] %s%e%n"
  banner:
    enabled: false
  mongodb:
    connection-string: ${ESTHESIS_DFL_ESTHESIS_DB_URL:}
    database: ${ESTHESIS_DFL_ESTHESIS_DB_NAME:}
    credentials:
      username: ${ESTHESIS_DFL_ESTHESIS_DB_USERNAME:}
      password: ${ESTHESIS_DFL_ESTHESIS_DB_PASSWORD:}
