quarkus:
  application:
    name: esthesis-dfl-orion-gateway
  container-image:
    group: esthesisiot
    name: esthesis-dfl-orion-gateway
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-20.20c{1.}] %s%e%n"
  opentelemetry:
    enabled: false
  banner:
    enabled: false

#esthesis:
#  dfl:
#    orion-retro-create-devices-schedule: "0 0 4/24 ? * * *"
