quarkus:
  live-reload:
    instrumentation: true
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  rest-client:
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  config:
    locations: "../../../../setup/dev/profiles"

