quarkus:
  http:
    host: 0.0.0.0
    cors: false
  rest-client:
    logging:
      scope: request-response
      body-limit: 16384
    RegistryResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
  log:
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
      esthesis:
        level: DEBUG
  opentelemetry:
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
