global:
  devEnv:
    enabled: false

mongodb:
  fullnameOverride: esthesis-mongodb
  auth:
    rootUser: root
    rootPassword: root
    usernames:
      - esthesis
    passwords:
      - esthesis
    databases:
      - esthesis
    replicaSetKey: esthesis
  arbiter:
    enabled: false
  serviceAccount:
    create: true
  rbac:
    create: true
  initdbScripts:
    addColMod.js: |
      use esthesis
      db.grantRolesToUser('esthesis', ["dbAdmin"])
