---
#image: gitpod/workspace-java-17
image: gitpod/workspace-full

additionalRepositories:
  - url: https://github.com/esthesis-iot/esthesis-setup
  - url: https://github.com/esthesis-iot/esthesis-ui
  - url: https://github.com/esthesis-iot/esthesis-docs
  - url: https://github.com/esthesis-iot/esthesis-device
  - url: https://github.com/esthesis-iot/esthesis-docker

workspaceLocation:
  esthesis-server/.code-workspace

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - redhat.vscode-xml
    - pivotal.vscode-spring-boot
    - asciidoctor.asciidoctor-vscode

tasks:
  - name: Supporting containers
    command: |
      docker compose \
        -f ../esthesis-setup/docker/docker-compose.yml \
        -f ../esthesis-setup/docker/docker-compose-devenv.yml \
        up \
        esthesis-db esthesis-mqtt esthesis-tsdb esthesis-nifi esthesis-chronograf
      gp sync-done docker
    openIn: right
  - name: Backend
    init: |
      mvn clean install -DskipTests=true
    command: |
      gp sync-await docker
      mvn spring-boot:run -Xdebug -XX:+ShowCodeDetailsInExceptionMessages \
        -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=55000 -Dspring-boot.run.arguments="--server.port=46000"
  - name: Frontend
    init: |
      cd ../esthesis-ui
      npm install
    command: |
      gp sync-done docker 
      cd ../esthesis-ui          
      ng serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.json

ports:
  - port: 3306
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
