---
#image: gitpod/workspace-java-17
image: gitpod/workspace-full

additionalRepositories:
  - url: https://github.com/esthesis-iot/esthesis-setup
  - url: https://github.com/esthesis-iot/esthesis-ui
  - url: https://github.com/esthesis-iot/esthesis-docs
  - url: https://github.com/esthesis-iot/esthesis-device
  - url: https://github.com/esthesis-iot/esthesis-docker

workspaceLocation:
  esthesis-server/.code-workspace

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - Pivotal.vscode-boot-dev-pack
    - redhat.vscode-xml
    - pivotal.vscode-spring-boot
    - asciidoctor.asciidoctor-vscode
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok

tasks:
  - name: Prepare env
    init: |
      docker compose \
        -f /workspace/esthesis-setup/docker/docker-compose.yml \
        -f /workspace/esthesis-setup/docker/docker-compose-devenv.yml \
        pull esthesis-db esthesis-mqtt esthesis-tsdb esthesis-nifi esthesis-chronograf
      yes | sdk install java 17.0.2-tem
      cd /workspace/esthesis-server && mvn clean install -DskipTests=true
      cd /workspace/esthesis-ui && npm install && npx -y @angular/cli build
    command: gp sync-done env

  - name: Supporting containers
    command: |
      gp sync-await env
      docker compose \
        -f /workspace/esthesis-setup/docker/docker-compose.yml \
        -f /workspace/esthesis-setup/docker/docker-compose-devenv.yml \
        up -d esthesis-db esthesis-mqtt esthesis-tsdb esthesis-nifi esthesis-chronograf
      gp sync-done docker
      docker compose \
        -f /workspace/esthesis-setup/docker/docker-compose.yml \
        -f /workspace/esthesis-setup/docker/docker-compose-devenv.yml \
        logs -f

  - name: Backend
    before: yes | sdk install java 17.0.2-tem
    command: |
      gp sync-await docker
      cd /workspace/esthesis-server/esthesis-server-impl
      mvn spring-boot:run \
        -Dspring-boot.run.jvmArguments="-Xdebug -XX:+ShowCodeDetailsInExceptionMessages -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=55000" \
        -Dspring-boot.run.arguments="--server.port=46000"

  - name: Frontend
    command: |
      gp sync-await docker
      cd /workspace/esthesis-ui
      npx -y @angular/cli serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.json

ports:
  - port: 3306
    name: MariaDB
    onOpen: ignore
  - port: 4200
    name: Angular App
    onOpen: open-preview
  - port: 8888
    onOpen: ignore
  - port: 8883
    name: mqqt-secure
    onOpen: ignore
  - port: 8086
    name: InfluxDB
    onOpen: ignore
  - port: 8080
    name: NiFi
    onOpen: ignore
  - port: 1883
    name: mqtt
    onOpen: ignore
  - port: 20000
    name: NiFi Digital Twins API
    onOpen: ignore