---
#image: gitpod/workspace-java-17
image: gitpod/workspace-full

tasks:
  - name: Backend
    init: |
      mvn clean install -DskipTests=true
    command: |
      mvn spring-boot:run -Xdebug -XX:+ShowCodeDetailsInExceptionMessages \
        -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=55000 -Dspring-boot.run.arguments="--server.port=46000"
