---
image: gitpod/workspace-java-17

additionalRepositories:
  - url: https://github.com/esthesis-iot/esthesis-setup
  - url: https://github.com/esthesis-iot/esthesis-ui
  - url: https://github.com/esthesis-iot/esthesis-docs
  - url: https://github.com/esthesis-iot/esthesis-device
  - url: https://github.com/esthesis-iot/esthesis-docker

workspaceLocation:
  esthesis-server/.code-workspace

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - redhat.vscode-xml
    - pivotal.vscode-spring-boot
    - asciidoctor.asciidoctor-vscode

tasks:
  - command: |
      docker compose \
        -f ../esthesis-setup/docker/docker-compose.yml \
        -f ../esthesis-setup/docker/docker-compose-devenv.yml \
        up -d \
        esthesis-db esthesis-mqtt esthesis-tsdb esthesis-nifi esthesis-chronograf

ports:
  - port: 3306
    onOpen: ignore