version: "3.9"

networks:
  esthesis:
    name: esthesis

volumes:
  esthesis-db-storage:
  esthesis-tsdb-storage:
  esthesis-nifi-storage:
  esthesis-server-storage:

services:
  esthesis-db:
    image: mariadb:10.7.1-focal
    hostname: esthesis-db
    container_name: esthesis-db
    restart: unless-stopped
    command: --max_allowed_packet=1024000000
    volumes:
      - "esthesis-db-storage:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE:-esthesis}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-root}"
      MARIADB_USER: "${MARIADB_USER:-esthesis}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD:-esthesis}"
    deploy:
      resources:
        limits:
          memory: "1G"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
      start_period: 10m
    networks:
      - esthesis

  esthesis-mqtt:
    image: eclipse-mosquitto:1.6.12
    hostname: esthesis-mqtt
    container_name: esthesis-mqtt
    restart: unless-stopped
    ports:
      - "${PORT_MQTT:-1883}:1883"
      - "${PORT_MQTT_SECURE:-8883}:8883"
    deploy:
      resources:
        limits:
          memory: "512M"
    healthcheck:
      test: nc -vz localhost 1883 || nc -vz localhost 8883
      start_period: 10m
    networks:
      - esthesis

  esthesis-tsdb:
    image: influxdb:1.7.8
    hostname: esthesis-tsdb
    container_name: esthesis-tsdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: "${INFLUXDB_DB:-esthesis}"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER:-admin}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD:-admin}"
    deploy:
      resources:
        limits:
          memory: "2G"
    volumes:
      - "esthesis-tsdb-storage:/var/lib/influxdb"
    healthcheck:
      test: curl -sI 127.0.0.1:8086/ping | grep -q "204 No Content"
      start_period: 10m
    networks:
      - esthesis

  esthesis-nifi:
    build:
      context: ../../esthesis-docker/esthesis-nifi
    image: esthesisiot/esthesis-nifi:1.10.0-2
    hostname: esthesis-nifi
    container_name: esthesis-nifi
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "2G"
    healthcheck:
      test: curl -sI http://esthesis-nifi:8080/nifi | grep -q "HTTP/1.1 302 Found"
      start_period: 10m
    networks:
      - esthesis

  esthesis-server:
    build:
      context: ./esthesis-server
    image: esthesisiot/esthesis-server:2.0.10
    hostname: esthesis-server
    container_name: esthesis-server
    restart: unless-stopped
    environment:
        spring_datasource_url: "jdbc:mariadb://esthesis-db:3306/esthesis?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        spring_datasource_username: "${MARIADB_USER:-esthesis}"
        spring_datasource_password: "${MARIADB_PASSWORD:-esthesis}"
    volumes:
      - "esthesis-server-storage:/home/users/esthesis/.esthesis"
    deploy:
      resources:
        limits:
          memory: "1G"
    healthcheck:
      test: curl -sI http://127.0.0.1:46000/api/ping | grep -q "HTTP/1.1 200"
      start_period: 10m
    depends_on:
      - esthesis-db
    networks:
      - esthesis

  esthesis-ui:
    build:
      context: ./esthesis-ui
    image: esthesisiot/esthesis-ui:2.0.10
    hostname: esthesis-ui
    container_name: esthesis-ui
    restart: unless-stopped
    environment:
      ESTHESIS_SERVER_HOSTNAME: "esthesis-server"
    deploy:
      resources:
        limits:
          memory: "256M"
    healthcheck:
      test: curl -sI http://127.0.0.1:80 | grep -q "HTTP/1.1 200"
      start_period: 10m
    depends_on:
      - esthesis-server
    networks:
      - esthesis
