version: "3.9"

volumes:
  esthesis-chronograf:

services:
  esthesis-db:
    ports:
      - "3306:3306"
  esthesis-mqtt:
    ports:
      - "1883:1883"
      - "8883:8883"
  esthesis-tsdb:
    ports:
      - "8086:8086"
  esthesis-nifi:
    ports:
      - "8080:8080"
      - "20000:20000"
  esthesis-chronograf:
    image: chronograf:1.6.2
    hostname: esthesis-chronograf
    container_name: esthesis-chronograf
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - "esthesis-chronograf:/var/lib/chronograf"
    command: chronograf --influxdb-url=http://esthesis-tsdb:8086
    deploy:
      resources:
        limits:
          memory: "1G"
#    healthcheck:
#      test: curl -sI 127.0.0.1:8088 | grep -q "200 OK"
#      start_period: 2m
    # networks:
    #   - esthesis
  zookeeper:
      image: confluentinc/cp-zookeeper:7.0.1
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:    
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1