quarkus:
  application:
    name: esthesis-srv-about
  container-image:
    group: esthesisiot
    name: esthesis-srv-about
  devservices:
    enabled: false
  log:
    level: WARN
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  opentelemetry:
    enabled: false

mp:
  jwt:
    verify:
      publickey:
        location: "http://esthesis-keycloak/realms/esthesis/protocol/openid-connect/certs"

