quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  rest-client:
    SettingsSystemResource:
      url: http://localhost:59030
      scope: Singleton
    CASystemResource:
      url: http://localhost:59040
      scope: Singleton
    DataflowSystemResource:
      url: http://localhost:59060
      scope: Singleton
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
    ProvisioningAgentResource:
      url: http://localhost:59100
      scope: Singleton
    SigningSystemResource:
      url: http://localhost:59040
      scope: Singleton
    InfrastructureSystemResource:
      url: http://localhost:59110
      scope: Singleton
  oidc:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  redis:
    hosts: redis://:esthesis@esthesis-dev-redis:6379/0
  config:
    locations: "../../../setup/dev/profiles/application-dev-profiles.yaml"

kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094

