quarkus:
  application:
    name: esthesis-srv-dataflow
  container-image:
    group: esthesisiot
    name: esthesis-srv-dataflow
  mongodb:
    connection-string: mongodb://mongodb:27017
    database: esthesis
    credentials:
      username: esthesis
      password: esthesis
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  opentelemetry:
    enabled: false
  rest-client:
    DockerClient:
      url: https://registry.hub.docker.com
      scope: Singleton

mp:
  jwt:
    verify:
      publickey:
        location: "http://esthesis-keycloak/realms/esthesis/protocol/openid-connect/certs"

esthesis:
  docker:
    dataflows:
      MQTT_CLIENT: "esthesisiot/esthesis-dfl-mqtt-client"
