quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    #      "org.jboss.resteasy.reactive.client.logging":
    #        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  rest-client:
    #    logging:
    #      scope: request-response
    #      body-limit: 65536
    RegistryResource:
      url: http://localhost:59030
      scope: Singleton
    TagResource:
      url: http://localhost:59020
      scope: Singleton
    KubernetesResource:
      url: http://localhost:59050
      scope: Singleton
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb-0:27017,esthesis-dev-mongodb-1:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs

kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094
