quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
      "org.mongodb":
        level: WARN
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  mongodb:
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  rest-client:
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
    SecurityResource:
      url: http://localhost:59170
      scope: Singleton
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  config:
    locations: "../../../../_dev/profiles"

kafka:
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: SCRAM-SHA-512
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username=esthesis-system password=esthesis-system;
