quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "localhost"
        port: 12201
  mongodb:
    connection-string: mongodb://mongodb-headless.esthesis:27017
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  rest-client:
    AuditResource:
      url: http://localhost:59140
  redis:
    hosts: redis://:esthesis-system@redis-master.esthesis:6379/0
  otel:
    sdk:
      disabled: false
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis/realms/esthesis/protocol/openid-connect/certs

kafka:
  bootstrap:
    servers:
      - kafka.esthesis:9092
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: SCRAM-SHA-512
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username=esthesis-system password=esthesis-system;

esthesis:
  oidc:
    authority: "http://keycloak.esthesis/realms/esthesis"
    redirect-url: "http://localhost:4200/callback"
    post-logout-redirect-uri: "http://localhost:4200/logged-out"
