quarkus:
  application:
    name: esthesis-core-srv-security
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-security
  mongodb:
    connection-string: mongodb://mongodb:27017
    database: esthesis
    credentials:
      username: esthesis
      password: esthesis
  devservices:
    enabled: false
  liquibase-mongodb:
    migrate-at-start: true
  log:
    level: WARN
    category:
      esthesis:
        level: INFO
      "org.jboss.resteasy.reactive":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  opentelemetry:
    enabled: false
