quarkus:
  live-reload:
    instrumentation: true
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: grafana-loki-gelf
        port: 12201
        include-full-mdc: true
        skip-hostname-resolution: true
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor:4317
  config:
    locations: "../../../../setup/dev/profiles"
