quarkus:
  live-reload:
    instrumentation: true
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "localhost"
        port: 12201
  otel:
    sdk:
      disabled: false
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor:4317
  config:
    locations: "../../../_dev/profiles"
