quarkus:
  application:
    name: esthesis-srv-public
  container-image:
    group: esthesisiot
    name: esthesis-srv-public
  devservices:
    enabled: false
  log:
    level: WARN
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  opentelemetry:
    enabled: false

esthesis:
  oidc:
    client-id: "esthesis"
    scope: "openid profile offline_access"
    response-type: "code"
    silent-renew: true
    use-refresh-token: true
    renew-time-before-token-expires-in-seconds: 30
    max-id-token-iat-offset-allowed-in-seconds: 10
    ignore-nonce-after-refresh: true
    secure-routes: [ "/api" ]
