{{ if .Values.global.devEnv.enabled }}
{{- $name := .Values.global.devEnv.ip | required ".Values.global.devEnv.ip is required." -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: esthesis-routes-dev-public-access
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: esthesis-routes-dev-public-access
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job-dev-routes-public-access
          image: "wbitt/network-multitool"
          command:
            - /bin/sh
            - -c
            - |
              while ! nc -z apisix-admin 9180; do sleep 1; done && \
              curl -s http://apisix-admin:9180/apisix/admin/routes/dev-srv-public-access-route -H "X-API-KEY: esthesis-admin" -X PUT -i -d '
              {
              "name": "dev-srv-public-access-route",
              "uris": ["/api/public-access", "/api/public-access/*"],
              "upstream": {
                "type": "roundrobin",
                "nodes": {
                    "{{ .Values.global.devEnv.ip }}:59160": 1
                }
              },
              "plugins": {
                "opentelemetry": {
                  "sampler": {
                    "name": "always_on"
                  }
                },
                "proxy-rewrite": {
                    "regex_uri": [
                      "/api/public-access/(.*)",
                      "/api/$1"
                    ]
                },
                "cors": {
                    "origin": "*"
                }
              }
              }'
  {{ end }}
