quarkus:
  application:
    name: esthesis-core-srv-campaign
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-campaign
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  zeebe:
    opentelemetry:
      enabled: false
    devservices:
      enabled: false
    client:
      security:
        plaintext: true
  oidc-client:
    client-id: esthesis
    grant:
      type: PASSWORD
  rest-client:
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
    DeviceResource:
      url: http://esthesis-core-srv-device-service:8080
      scope: Singleton
    CommandSystemResource:
      url: http://esthesis-core-srv-command-service:8080
      scope: Singleton
