quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        include-full-mdc: true
        skip-hostname-resolution: true
  mongodb:
    connection-string: mongodb://mongodb.esthesis.localdev:27017
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  redis:
    hosts: redis://:esthesis-system@redis.esthesis.localdev:6379/0
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  oidc-client:
    auth-server-url: http://keycloak.esthesis.localdev/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  rest-client:
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
    DeviceResource:
      url: http://localhost:59010
      scope: Singleton
    CommandSystemResource:
      url: http://localhost:59080
      scope: Singleton
  zeebe:
    opentelemetry:
      enabled: true
    client:
      broker:
        gateway-address: camunda-zeebe-gateway.esthesis.localdev:26500
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
