quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  redis:
    hosts: redis://:esthesis@esthesis-dev-redis:6379/0
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
#  oidc:
#    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
#    client-id: esthesis
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  rest-client:
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
    DeviceResource:
      url: http://localhost:59010
      scope: Singleton
    CommandSystemResource:
      url: http://localhost:59080
      scope: Singleton
  zeebe:
    opentelemetry:
      enabled: true
    client:
      broker:
        gateway-address: esthesis-dev-camunda-zeebe-gateway:26500
  config:
    locations: "../../../../setup/dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
