####################################################################################################
# esthesis-ui
####################################################################################################

####################################################################################################
# Service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ui-service
spec:
  selector:
    app: esthesis-ui
  ports:
    - port: 80
  type: {{ .Values.serviceType }}

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-ui-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-ui
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: esthesis-ui
    spec:
      containers:
        - name: esthesis-ui
          image: esthesisiot/esthesis-ui:2.0.17
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ESTHESIS_SERVER_HOSTNAME
              value: esthesis-server-service
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 2
