quarkus:
  live-reload:
    instrumentation: true
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        skip-hostname-resolution: true
  rest-client:
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  otel:
    sdk:
      disabled: false
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor:4317
  config:
    locations: "../../../_dev/profiles"

