quarkus:
  live-reload:
    instrumentation: true
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  rest-client:
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
  oidc-client:
    auth-server-url: http://keycloak.esthesis/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor:4317
  config:
    locations: "../../../_dev/profiles"

