quarkus:
  application:
    name: esthesis-core-dfl-orion-gateway
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-20.20c{1.}] %s%e%n"
    handler:
      gelf:
        include-full-mdc: true
        skip-hostname-resolution: false
        additional-field:
          platform:
            value: esthesis
          module:
            value: esthesis-core
          type:
            value: Dataflow
          service:
            value: ${quarkus.application.name}
  banner:
    enabled: false
  otel:
    sdk:
      disabled: true
  cache:
    caffeine:
      "is-data-update-allowed":
        expire-after-write: ${ESTHESIS_DFL_CACHE_IS_DATA_UPDATE_ALLOWED_EXPIRATION:24H}
  rest-client:
    DeviceSystemResource:
      scope: Singleton
  redis:
    hosts: ${ESTHESIS_DFL_REDIS_URL:}
  # Do not remove the following configuration, it is needed, so that it can be overridden in runtime
  # (otherwise environment variables such as QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_PASSWORD_USERNAME
  # are ignored (see https://github.com/quarkusio/quarkus/discussions/41259#discussioncomment-9795685).
  oidc-client:
    grant-options:
      password:
        username: defined-in-runtime
        password: defined-in-runtime
