quarkus:
  application:
    name: esthesis-core-dfl-rdbms-writer
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-30.30c{1.}] %s%e%n"
    handler:
      gelf:
        include-full-mdc: true
        skip-hostname-resolution: false
        additional-field:
          platform:
            value: esthesis
          module:
            value: esthesis-core
          type:
            value: Dataflow
          service:
            value: ${quarkus.application.name}
  banner:
    enabled: false
  datasource:
    # "mysql" should not be needed below, however leaving this parameter empty results in
    # "The Agroal dependency is present but no JDBC datasources have been defined.". To be
    # rechecked in future Quarkus versions.
    db-kind: ${ESTHESIS_DFL_DB_KIND:mysql}
    username: ${ESTHESIS_DFL_DB_USERNAME:}
    password: ${ESTHESIS_DFL_DB_PASSWORD:}
    jdbc:
      url: ${ESTHESIS_DFL_DB_JDBC_URL:}
  otel:
    sdk:
      disabled: true
