quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  config:
    locations: "../../../../setup/dev/profiles"

esthesis:
  oidc:
    authority: "http://esthesis-dev-keycloak/realms/esthesis"
    redirect-url: "http://localhost:4200/callback"
    post-logout-redirect-uri: "http://localhost:4200/logged-out"
