quarkus:
  rest-client:
    logging:
      scope: request-response
      body-limit: 4096
    RegistryResource:
      url: http://localhost:59030
      scope: Singleton
  log:
    category:
      "org.apache.http":
        level: DEBUG
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
