####################################################################################################
# esthesis tsdb
####################################################################################################

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-tsdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.global.storageClassName }}

####################################################################################################
# Service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-tsdb-service
spec:
  selector:
    app: esthesis-tsdb
  ports:
    - port: 8086
      name: http
      targetPort: 8086
    - port: 8088
      name: rpc
      targetPort: 8088

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-tsdb-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-tsdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: esthesis-tsdb
    spec:
      containers:
        - name: esthesis-ds-influxdb
          image: influxdb:1.7.9
          ports:
            - containerPort: 8086
            - containerPort: 8088
          env:
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esthesis-secret
                  key: tsdb_admin_password
            - name: INFLUXDB_ADMIN_USER
              value: "esthesis"
            - name: INFLUXDB_DB
              value: "esthesis"
            - name: INFLUXDB_BIND_ADDRESS
              value: ":8088"
          volumeMounts:
            - mountPath: "/var/lib/influxdb"
              name: esthesis-tsdb-pv
          startupProbe:
            httpGet:
              path: /ping
              port: 8086
            periodSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 2
          resources:  
            limits: 
              cpu: 500m 
              memory: 512Mi 
            requests: 
              cpu: 250m 
              memory: 512Mi
      volumes:
        - name: esthesis-tsdb-pv
          persistentVolumeClaim:
            claimName: esthesis-tsdb-pvc
