quarkus:
  application:
    name: esthesis-core-dfl-redis-cache
  container-image:
    group: esthesisiot
    name: esthesis-core-dfl-redis-cache
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-30.30c{1.}] %s%e%n"
    handler:
      gelf:
        additional-field:
          "platform":
            value: "esthesis"
          "module":
            value: esthesis-core
          "type":
            value: "API"
          "service":
            value: ${quarkus.application.name}
  banner:
    enabled: false
  redis:
    hosts: ${ESTHESIS_DFL_REDIS_URL:}
  opentelemetry:
    enabled: false
