quarkus:
  application:
    name: esthesis-core-srv-provisioning
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-provisioning
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  index-dependency:
    fileupload:
      group-id: io.quarkus.resteasy.reactive
      artifact-id: resteasy-reactive-common
  oidc-client:
    client-id: esthesis
    grant:
      type: PASSWORD
  rest-client:
    DeviceSystemResource:
      url: http://esthesis-core-srv-device-service:8080
      scope: Singleton
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
