quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
      "io.quarkus.oidc.token.propagation.reactive":
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true

  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017

  rest-client:
    logging:
      scope: request-response
      body-limit: 65536

  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
