###############################################################################
# DEV PROFILES
###############################################################################
"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy.reactive":
          level: DEBUG
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536
"%debug-mongo":
  quarkus:
    log:
      category:
        "io.quarkus.mongodb.panache.common.runtime":
          level: DEBUG
"%debug-token":
  quarkus:
    log:
      category:
        "io.quarkus.oidc.token.propagation.reactive":
          level: DEBUG
"%debug-camel":
  quarkus:
    log:
      category:
        "org.apache.camel":
          level: DEBUG
"%trace":
  quarkus:
    log:
      category:
        esthesis:
          level: TRACE
