# gcr.io/distroless/static-debian12:nonroot-amd64
FROM gcr.io/distroless/static-debian12@sha256:22cda3953e236576e5d113fc6a9290b27e179fbe5937efb1fdc16d81ddfb6120
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
