# gcr.io/distroless/static-debian12:nonroot-arm64
FROM gcr.io/distroless/static-debian12@sha256:9e135e71d890b8d72f922df929360939921844266906776acc7574712668c582
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
