# gcr.io/distroless/static-debian12:debug-nonroot-arm
FROM gcr.io/distroless/static-debian12@sha256:5f56bafd2d55352f4c69fd7bf5ca3df3ba6f36aecce7682a2aff6cb07784da22
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
