FROM golang:1.21.3-bookworm as build

WORKDIR /app
COPY go/. .
RUN go mod download
RUN go build -o esthesis-core-device -ldflags '-linkmode external -w -extldflags "-static"' cmd/main.go

FROM alpine:3.18.4
RUN mkdir -p /app/.esthesis
COPY --from=build /app/esthesis-core-device /app/esthesis-core-device
COPY go/scripts/samples/provisioning-handlers/firmware-update.sh /app/.esthesis/firmware-update.sh
COPY go/scripts/samples/version/version /app/.esthesis/version
EXPOSE 8080 1883

# Specifies the executable command that runs when the container starts
CMD ["/app/esthesis-core-device"]
