# gcr.io/distroless/static-debian12:nonroot-arm
FROM gcr.io/distroless/static-debian12@sha256:e843e44d07f9d6fb5fa5a5eee40c16d8e70eba60b8def5a4bc52ad2d996d1968
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
