# gcr.io/distroless/static-debian12:debug-nonroot-arm64
FROM gcr.io/distroless/static-debian12@sha256:4a3d6125fc7e16095972a8f243aa7bd46724912a9614f8e06c6554563e21b3b6
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/.esthesis/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
