# gcr.io/distroless/static-debian12:debug-nonroot-amd64
FROM gcr.io/distroless/static-debian12@sha256:20ae390b2f5dfc3d58295b93cccbe3b07d39c943ef8e0fdd0eff26a1257eb70c
LABEL maintainer="esthesis@eurodyn.com"

COPY --chown=65532:65532 go/scripts/samples/provisioning-handlers/firmware-update.sh /app/
COPY --chown=65532:65532 go/scripts/samples/version/version /app/version
COPY --chown=65532:65532 native/esthesis-core-device-linux-amd64 /app/esthesis-core-device
EXPOSE 8080 1883

ENTRYPOINT ["/app/esthesis-core-device"]
