quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  rest-client:
    DataflowSystemResource:
      url: http://localhost:59060
      scope: Singleton
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317
  redis:
    hosts: redis://:esthesis@esthesis-dev-redis:6379/0

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs

###############################################################################
# DEBUG PROFILES
###############################################################################
"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy.reactive":
          level: DEBUG
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536
"%debug-mongo":
  quarkus:
    log:
      category:
        "io.quarkus.mongodb.panache.common.runtime":
          level: DEBUG
"%debug-token":
  quarkus:
    log:
      category:
        "io.quarkus.oidc.token.propagation.reactive":
          level: DEBUG
"%debug-camel":
  quarkus:
    log:
      category:
        "org.apache.camel":
          level: DEBUG
