quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  mongodb:
    connection-string: mongodb://mongodb-headless.esthesis:27017
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  rest-client:
    SettingsSystemResource:
      url: http://localhost:59030
      scope: Singleton
    CASystemResource:
      url: http://localhost:59040
      scope: Singleton
    DataflowSystemResource:
      url: http://localhost:59060
      scope: Singleton
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
    ProvisioningAgentResource:
      url: http://localhost:59100
      scope: Singleton
    SigningSystemResource:
      url: http://localhost:59040
      scope: Singleton
    InfrastructureSystemResource:
      url: http://localhost:59110
      scope: Singleton
  oidc-client:
    auth-server-url: http://keycloak.esthesis/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  redis:
    hosts: redis://:esthesis-system@redis-master.esthesis:6379/0
  config:
    locations: "../../../../_dev/profiles"

kafka:
  bootstrap:
    servers:
      - kafka.esthesis:9092
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: SCRAM-SHA-512
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username=esthesis-system password=esthesis-system;

