quarkus:
  log:
    level: ERROR
  devservices:
    enabled: true
    timeout: 5m
  kafka:
    devservices:
      enabled: false
      image-name: bitnami/kafka:3.6.1
  mongodb:
    database: esthesiscore-test
    devservices:
      enabled: true
      image-name: "mongo:7.0.5"
  keycloak:
    devservices:
      enabled: false
  oidc:
    auth-server-url: "http://locahost:45123"
    devservices:
      enabled: false
  rest-client:
    SettingsSystemResource:
      url: http://localhost:59030
      scope: Singleton
    CASystemResource:
      url: http://localhost:59040
      scope: Singleton
    DataflowSystemResource:
      url: http://localhost:59060
      scope: Singleton
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
    ProvisioningSystemResource:
      url: http://localhost:59100
      scope: Singleton
    SigningSystemResource:
      url: http://localhost:59040
      scope: Singleton
    InfrastructureSystemResource:
      url: http://localhost:59110
      scope: Singleton
  http:
    test-port: 0
