quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
      "org.mongodb":
        level: WARN
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  config:
    locations: "../../../../_dev/profiles"
  rest-client:
    SecurityResource:
      url: http://localhost:59170
      scope: Singleton
