{{- if .Values.global.devEnv.enabled -}}
{{- $name := .Values.global.devEnv.ip | required ".Values.global.devEnv.ip is required." -}}

apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: srv-tag-dev-route
spec:
  http:
    - name: srv-tag-dev-route-v1
      match:
        paths:
          - "/api/v1/tag"
          - "/api/v1/tag/*"
      backends:
        - serviceName: {{ .Release.Name }}-tag-device
          servicePort: 8080
      plugins:
        - name: opentelemetry
          enabled: true
          config:
            sampler: always_on
        - name: proxy-rewrite
          enabled: true
          config:
            regex_uri: [ "/dev/(.*)", "/$1" ]
        - name: openid-connect
          enable: true
          config:
            client_id: esthesis
            client_secret: ""
            discovery: http://192.168.21.3/realms/esthesis/.well-known/openid-configuration
            scope: "openid profile"
            use_jwks: true
            bearer_only: true
            realm: esthesis
            redirect_uri: /dev/api/v1/tag/callback
            set_access_token_header: false
            set_id_token_header: false
            set_userinfo_header: false
{{- end }}
