global:
  devEnv:
    enabled: true
    ip:
    servicePorts:
      tag: 59020

  conf:
    jaeger:
      ui:
        serviceType: LoadBalancer
      collector:
        serviceType: LoadBalancer

apisix:
  admin:
    type: LoadBalancer
apisix-dashboard:
  service:
    type: LoadBalancer
mongodb:
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
    service:
      type: LoadBalancer
  serviceAccount:
    create: true
  rbac:
    create: true
kafka:
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true
    service:
      type: LoadBalancer
  serviceAccount:
    create: true
  rbac:
    create: true
#minio:
#  consoleService:
#    type: LoadBalancer
grafana:
  service:
    type: LoadBalancer
