version: "3.9"

volumes:
  esthesis-mongo-storage:
  esthesis-influxdb-storage:
  esthesis-chronograf-storage:

services:
  devenv:
    build :
      dockerfile: .devcontainer/Dockerfile
      context: .
      args:
        - VARIANT=17-bullseye
        - INSTALL_MAVEN=true
        - MAVEN_VERSION=3.8.4
        - NODE_VERSION=16
    command: sleep infinity
    volumes:
      - .:/workspace
  mosquitto:
      image: eclipse-mosquitto:1.6.12
      hostname: esthesis-mqtt
      container_name: esthesis-mqtt
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "8883:8883"
      deploy:
        resources:
          limits:
            memory: "512M"
      healthcheck:
        test: nc -vz localhost 1883 || nc -vz localhost 8883
        start_period: 10m
  influxdb:
    image: influxdb:1.7.8
    hostname: esthesis-tsdb
    container_name: esthesis-tsdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: "${INFLUXDB_DB:-esthesis}"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER:-admin}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD:-admin}"
    deploy:
      resources:
        limits:
          memory: "2G"
    volumes:
      - "esthesis-influxdb-storage:/var/lib/influxdb"
    healthcheck:
      test: curl -sI 127.0.0.1:8086/ping | grep -q "204 No Content"
      start_period: 10m
  chronograf:
    image: chronograf:1.6.2
    hostname: esthesis-chronograf
    container_name: esthesis-chronograf
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - "esthesis-chronograf-storage:/var/lib/chronograf"
    command: chronograf --influxdb-url=http://esthesis-tsdb:8086
    deploy:
      resources:
        limits:
          memory: "1G"
  zookeeper:
      image: confluentinc/cp-zookeeper:7.0.1
      container_name: esthesis-zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: esthesis-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'esthesis-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  mongo:
    image: mongo:4.4.14-focal
    container_name: esthesis-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - "esthesis-mongo-storage:/data/db"