quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "localhost"
        port: 12201
  otel:
    sdk:
      disabled: false
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  # TODO document how to get these
#  kubernetes-client:
#    ca-cert-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTlRVeU9EYzNPVEV3SGhjTk1qSXdOakUxTVRBd09UVXhXaGNOTXpJd05qRXlNVEF3T1RVeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTlRVeU9EYzNPVEV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTbklXbUw2YjdXenlyR0xmNGt1RjBralRaTGhRSUV0ZzljYzZQclFudngKVkM1MGQ4VVhwRDkxOFdvNjN5K09BMWVqVys0QnhUaG12dTY1UjBHMmJZVVZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlJUHpqem9qaGoxVnUra2N2YkJJCm8vTDliM0F3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9qaFpieEI0VlVSait1ZWNXbk9mMFl4d2c4MkpGZEEKVU9jZjhGSlhvdytWQWlFQTEyc016ejZ2OXJkSDNTVjNyWHN2R3FyVGtoMjJoMjBvYlRCTWp0bzZ2dzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#    client-cert-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJWUNIQ1N0Q1p0RFF3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalV5TmpNNE5EUXlNQjRYRFRJeU1EVXhOVEU0TVRRd01sb1hEVEl6TURVeApOVEU0TVRRd01sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCMW5uQWJNY2k5NklBZHIKcVhMa2FpbW1pVGUySmpaSGVZdXBRWGFWdVVNY20zbjBad3hyR0tKWjBYaVZhcElGMVljdEtqRGUza1ZSd2ZDVwpxS00rN3dtalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUTcyUnR4YTI0cjhCZGdrZUlGMFlaMmREU3VpekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQWw0VHV2VUN4MUtDa1F3RlZTUHltRDBER2FCRkFYcHR0T1JRajVBcUMxVk1DSVFEaitWUmxrR3hucHJDTgpWeFl2SEdQd0x6WGlKWG5vM0x0QXlPVG9RODdpNVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFMk5USTJNemcwTkRJd0hoY05Nakl3TlRFMU1UZ3hOREF5V2hjTk16SXdOVEV5TVRneE5EQXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFMk5USTJNemcwTkRJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUjZHVzUwOE9YbU5wMFdiKy9jajNXSG9pNVJkeGdHZWlRb2U2TUdNQ2xvCnFMU2FlMVI4Z3cxOEFMcTZ0Zi9UZVB2b0t2ZWVZZFB2Y0ZYK3ZScGhwQUgzbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVPOWtiY1d0dUsvQVhZSkhpQmRHRwpkblEwcm9zd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ2VVMUwwVlpMb2NpM1liNTl4UUNKTTJTWlBVU3BQSXh5CllscHVaZk5SYjNBQ0lFd0VUNGNkdy9YNUd5T0dpL3hEUFF5SWZKTFo1am51Z2FIa2E5NzNKSjJrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1FL0dlMmZNS3FIQmhUUlRlR0RsTUhGazFzQU82RjZVRUp4cFJVYzNPRlVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSFdlY0JzeHlMM29nQjJ1cGN1UnFLYWFKTjdZbU5rZDVpNmxCZHBXNVF4eWJlZlJuREdzWQpvbG5SZUpWcWtnWFZoeTBxTU43ZVJWSEI4SmFvb3o3dkNRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis/realms/esthesis/protocol/openid-connect/certs
