quarkus:
  application:
    name: esthesis-core-srv-kubernetes
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-kubernetes
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
