quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        include-full-mdc: true
        skip-hostname-resolution: true
  mongodb:
    connection-string: mongodb://mongodb.esthesis.localdev:27017
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  rest-client:
    SettingsSystemResource:
      url: http://localhost:59030
      scope: Singleton
    CASystemResource:
      url: http://localhost:59040
      scope: Singleton
    DataflowSystemResource:
      url: http://localhost:59060
      scope: Singleton
    DeviceSystemResource:
      url: http://localhost:59010
      scope: Singleton
    ProvisioningAgentResource:
      url: http://localhost:59100
      scope: Singleton
    SigningSystemResource:
      url: http://localhost:59040
      scope: Singleton
    InfrastructureSystemResource:
      url: http://localhost:59110
      scope: Singleton
#  oidc:
#    auth-server-url: http://keycloak.esthesis.localdev/realms/esthesis
#    client-id: esthesis
  oidc-client:
    auth-server-url: http://keycloak.esthesis.localdev/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  redis:
    hosts: redis://:esthesis-system@redis.esthesis.localdev:6379/0
  config:
    locations: "../../../../_dev/profiles"

kafka:
  bootstrap:
    servers:
      - kafka.esthesis.localdev:9094

