apiVersion: v2
name: esthesis-platform
description: A Helm chart to deploy eshtesis IoT platform.
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: 2.0.12
