quarkus:
  application:
    name: esthesis-core-srv-audit
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-audit
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  http:
    limits:
      max-body-size: 16m
      max-form-attribute-size: 16m
  rest-client:
    # A self-reference to be able to use the Audited annotation.
    AuditResource:
      url: http://esthesis-core-srv-audit:8080
      scope: Singleton
