quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        skip-hostname-resolution: true
  mongodb:
    connection-string: mongodb://mongodb.esthesis.localdev:27017
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  config:
    locations: "../../../../_dev/profiles"
  rest-client:
    # A self-reference to be able to use the Audited annotation.
    AuditResource:
      url: http://localhost:59140
      scope: Singleton

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis.localdev/realms/esthesis/protocol/openid-connect/certs
