quarkus:
  http:
    host: 0.0.0.0
    cors: false
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  rest-client:
    # A self-reference to be able to use the Audited annotation.
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
  config:
    locations: "../../../setup/dev/profiles/application-dev-profiles.yaml"

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
