quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  rest-client:
    SettingsResource:
      url: http://localhost:59030
      scope: Singleton
    TagResource:
      url: http://localhost:59020
      scope: Singleton
    KubernetesResource:
      url: http://localhost:59050
      scope: Singleton
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  config:
    locations: "../../../../setup/dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094
