quarkus:
  log:
    level: INFO
  devservices:
    enabled: true
    timeout: 5m
  mongodb:
    database: esthesiscore-test
    devservices:
      enabled: true
      image-name: "mongo:7.0.5"
  http:
    test-port: 0
  liquibase-mongodb:
    migrate-at-start: false
