quarkus:
  log:
    level: INFO
  devservices:
    enabled: true
    timeout: 5m
  kafka:
    devservices:
      enabled: false
      image-name: bitnami/kafka:3.6.1
  mongodb:
    database: esthesiscore-test
    devservices:
      enabled: true
      image-name: mongo:7.0
  keycloak:
    devservices:
      enabled: false
  oidc:
    enabled: false
  redis:
    devservices:
      image-name: redis:7
  zeebe:
    devservices:
      image-name: camunda/zeebe:8.3.1
  http:
    test-port: 0
  liquibase-mongodb:
    migrate-at-start: false
