quarkus:
  application:
    name: esthesis-core-srv-provisioning
  http:
    limits:
      max-body-size: 256M
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    handler:
      gelf:
        include-full-mdc: true
        skip-hostname-resolution: false
        additional-field:
          platform:
            value: esthesis
          module:
            value: esthesis-core
          type:
            value: API
          service:
            value: ${quarkus.application.name}
  banner:
    enabled: false
  otel:
    sdk:
      disabled: true
#  index-dependency:
#    fileupload:
#      group-id: io.quarkus.resteasy.reactive
#      artifact-id: resteasy-reactive-common
  rest-client:
    DeviceSystemResource:
      url: http://esthesis-core-srv-device-service:8080
      scope: Singleton
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
    SettingsResource:
      url: http://esthesis-core-srv-settings-service:8080
      scope: Singleton
  # Do not remove the following configuration, it is needed, so that it can be overridden in runtime
  # (otherwise environment variables such as QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_PASSWORD_USERNAME
  # are ignored (see https://github.com/quarkusio/quarkus/discussions/41259#discussioncomment-9795685).
  oidc-client:
    grant-options:
      password:
        username: defined-in-runtime
        password: defined-in-runtime
