quarkus:
  application:
    name: esthesis-core-srv-tag
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-tag
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  rest-client:
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
    SecurityResource:
      url: http://esthesis-core-srv-security-service:8080
      scope: Singleton
mp:
  messaging:
    outgoing:
      esthesis-app-out:
        topic: esthesis-app
