quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        skip-hostname-resolution: true
  mongodb:
    connection-string: mongodb://mongodb.esthesis:27017
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  otel:
    sdk:
      disabled: false
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  rest-client:
    AuditResource:
      url: http://localhost:59140
    SecurityResource:
      url: http://localhost:59170
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis/realms/esthesis/protocol/openid-connect/certs

kafka:
  bootstrap:
    servers:
      - kafka.esthesis:9095
