quarkus:
  application:
    name: esthesis-core-dfl-command-reply-updater
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-20.20c{1.}] %s%e%n"
    handler:
      gelf:
        include-full-mdc: true
        skip-hostname-resolution: false
        additional-field:
          platform:
            value: esthesis
          module:
            value: esthesis-core
          type:
            value: Dataflow
          service:
            value: ${quarkus.application.name}
  banner:
    enabled: false
  otel:
    sdk:
      disabled: true
  mongodb:
    connection-string: ${ESTHESIS_DFL_ESTHESIS_DB_URL:}
    database: ${ESTHESIS_DFL_ESTHESIS_DB_NAME:}
    credentials:
      username: ${ESTHESIS_DFL_ESTHESIS_DB_USERNAME:}
      password: ${ESTHESIS_DFL_ESTHESIS_DB_PASSWORD:}
