quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        host: "localhost"
        port: 12201
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  rest-client:
    DeviceResource:
      url: http://localhost:59010
      scope: Singleton
  config:
    locations: "../../../../_dev/profiles"
  langchain4j:
    ollama:
      base-url: "http://ollama.esthesis:11434"

