global:
  devEnv:
    enabled: false

prometheus:
  alertmanager:
    enabled: false
  exporters:
    node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: false
  kubelet:
    enabled: false
  blackboxExporter:
    enabled: false
  coreDns:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeApiServer:
    enabled: false
  prometheus:
    additionalScrapeConfigs:
      enabled: true
      type: external
      external:
        name: prometheus-scrapers-config
        key: config.yaml
