quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        skip-hostname-resolution: true
  rest-client:
    ApplicationSystemResource:
      url: http://localhost:59090
      scope: Singleton
  oidc-client:
    auth-server-url: http://keycloak.esthesis.localdev/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  redis:
    hosts: redis://:esthesis-system@redis.esthesis.localdev:6379/0
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis.localdev/realms/esthesis/protocol/openid-connect/certs

