apiVersion: v2
name: esthesis
description: esthesis IoT platform - Camunda
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: 3.0.0-SNAPSHOT

dependencies:
  - name: camunda-platform
    alias: camunda
    version: 8.1.3
    repository: https://helm.camunda.io
