global:
  devEnv:
    enabled: false

keycloak:
  auth:
    adminUser: esthesis
    adminPassword: esthesis
    managementUser: esthesis
    managementPassword: esthesis
  postgresql:
    auth:
      postgresPassword: esthesis
      password: esthesis
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-config
