quarkus:
  log:
    level: ERROR
  devservices:
    enabled: true
    timeout: 5m
  kafka:
    devservices:
      enabled: false
      image-name: bitnami/kafka:3.6.1
  keycloak:
    devservices:
      enabled: false
  oidc:
    auth-server-url: "http://locahost:45123"
    devservices:
      enabled: false
  http:
    test-port: 0
