apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        isDefault: true
        url: http://loki-gateway:80
