quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  rest-client:
    ApplicationSystemResource:
      url: http://localhost:59090
      scope: Singleton
    CommandSystemResource:
      url: http://localhost:59080
      scope: Singleton
  oidc-client:
    auth-server-url: http://keycloak.esthesis/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  redis:
    hosts: redis://:esthesis-system@redis-master.esthesis:6379/0
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis/realms/esthesis/protocol/openid-connect/certs

