quarkus:
  log:
    level: INFO
  devservices:
    enabled: true
    timeout: 5m
  kafka:
    devservices:
      enabled: false
      image-name: bitnami/kafka:3.6.1
  mongodb:
    database: esthesiscore-test
    devservices:
      enabled: true
      image-name: "mongo:7.0.5"
  keycloak:
    devservices:
      enabled: false
  oidc:
    auth-server-url: "http://locahost:45123"
    devservices:
      enabled: false
  http:
    test-port: 0
esthesis:
  dt-api:
    timeout-in-ms: ${DT_API_REQUEST_TIMEOUT_MS:1000}
    poll-interval-in-ms: ${DT_API_REQUEST_POLL_INTERVAL_MS:100}
