quarkus:
  application:
    name: esthesis-core-srv-dt
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    handler:
      gelf:
        include-full-mdc: true
        skip-hostname-resolution: false
        additional-field:
          platform:
            value: esthesis
          module:
            value: esthesis-core
          type:
            value: API
          service:
            value: ${quarkus.application.name}
  banner:
    enabled: false
  otel:
    sdk:
      disabled: true
  swagger-ui:
    always-include: true
    path: /api/openapi-ui
    title: esthes.is Digital Twin API
    operations-sorter: alpha
    tags-sorter: alpha
    urls:
      default: /api/dt/openapi
  smallrye-openapi:
    path: /api/openapi
  oidc-client:
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: ${OIDC_CLIENT_USERNAME}
        password: ${OIDC_CLIENT_PASSWORD}
  rest-client:
    ApplicationSystemResource:
      url: http://esthesis-core-srv-application-service:8080
      scope: Singleton
