quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  redis:
    hosts: redis://:esthesis@esthesis-dev-redis:6379/0
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317
  rest-client:
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
    DeviceResource:
      url: http://localhost:59010
      scope: Singleton
    CommandSystemResource:
      url: http://localhost:59080
      scope: Singleton
  oidc:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    client-id: esthesis
    grant:
      type: PASSWORD
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  kogito:
    devservices:
      # remove once 1.33 becomes available
      image-name: quay.io/kiegroup/kogito-data-index-ephemeral
      image-version: 1.32
#  infinispan-client:
#    hosts: localhost:11222
#    username: esthesis
#    password: esthesis

#kafka:
#  bootstrap:
#    servers:
#      - esthesis-dev-kafka:9094

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs

esthesis:
  kogito:
    client:
      url: http://localhost:59150


###############################################################################
# DEBUG PROFILES
###############################################################################
"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy.reactive":
          level: DEBUG
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536

"%debug-mongo":
  quarkus:
    log:
      category:
        "io.quarkus.mongodb.panache.common.runtime":
          level: DEBUG

"%debug-token":
  quarkus:
    log:
      category:
        "io.quarkus.oidc.token.propagation.reactive":
          level: DEBUG

"%debug-kie":
  quarkus:
    log:
      category:
        "org.kie":
          level: DEBUG
