quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        skip-hostname-resolution: true
  mongodb:
    connection-string: mongodb://mongodb.esthesis.localdev:27017
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  rest-client:
    DataflowSystemResource:
      url: http://localhost:59060
    AuditResource:
      url: http://localhost:59140
  redis:
    hosts: redis://:esthesis-system@redis.esthesis.localdev:6379/0
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  oidc-client:
    auth-server-url: http://keycloak.esthesis.localdev/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  config:
    locations: "../../../../_dev/profiles"

mp:
  jwt:
    verify:
      publickey:
        location: http://keycloak.esthesis.localdev/realms/esthesis/protocol/openid-connect/certs

esthesis:
  oidc:
    authority: "http://esthesis-dev-keycloak/realms/esthesis"
    redirect-url: "http://localhost:4200/callback"
    post-logout-redirect-uri: "http://localhost:4200/logged-out"
