quarkus:
  application:
    name: esthesis-dfl-redis-cache
  container-image:
    group: esthesisiot
    name: esthesis-dfl-redis-cache
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-30.30c{1.}] %s%e%n"
  banner:
    enabled: false
  redis:
    hosts: ${ESTHESIS_DFL_REDIS_URL:}
