quarkus:
  application:
    name: esthesis-dfl-mqtt-client
  container-image:
    group: esthesisiot
    name: esthesis-dfl-mqtt-client
  devservices:
    enabled: false
  log:
    min-level: TRACE
    level: ${ESTHESIS_DFL_LOGGING_COMMON:INFO}
    category:
      esthesis:
        level: ${ESTHESIS_DFL_LOGGING_ESTHESIS:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%-20.20c{1.}] %s%e%n"
  banner:
    enabled: false
  opentelemetry:
    enabled: false
