quarkus:
  application:
    name: esthesis-core-srv-infrastructure
  container-image:
    group: esthesisiot
    name: esthesis-core-srv-infrastructure
  devservices:
    enabled: false
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    handler:
      gelf:
        additional-field:
          "platform":
            value: "esthesis"
          "module":
            value: esthesis-core
          "type":
            value: "API"
          "service":
            value: ${quarkus.application.name}
  banner:
    enabled: false
  otel:
    sdk:
      disabled: true
  oidc-client:
    client-id: esthesis
    grant:
      type: PASSWORD
  rest-client:
    TagSystemResource:
      url: http://esthesis-core-srv-tag-system:8080
      scope: Singleton
    AuditResource:
      url: http://esthesis-core-srv-audit-service:8080
      scope: Singleton
