quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector-grpc:4317
  oidc-client:
    auth-server-url: http://esthesis-dev-keycloak/realms/esthesis
    grant-options:
      password:
        username: esthesis-system
        password: esthesis-system
  rest-client:
    DeviceResource:
      url: http://localhost:59010
      scope: Singleton
    TagResource:
      url: http://localhost:59020
      scope: Singleton
    SettingsResource:
      url: http://localhost:59030
      scope: Singleton
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
  config:
    locations: "../../../../setup/dev/profiles"

kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs
