spring:
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  jackson:
    default-property-inclusion: non_empty
  jmx:
    enabled: false
  thymeleaf:
    cache: false

logging:
  level:
    esthesis: trace
    root: warn
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %highlight(%-3level) %white(%msg) - %green(%logger{36}) %n'
server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-connections: 16
    threads:
      max: 4
