###############################################################################
# DEV PROFILES
###############################################################################
"%debug":
  quarkus:
    log:
      category:
        esthesis:
          min-level: TRACE
          level: DEBUG
"%trace":
  quarkus:
    log:
      category:
        esthesis:
          min-level: TRACE
          level: TRACE
"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy":
          min-level: TRACE
          level: TRACE
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536
"%debug-mongodb":
  quarkus:
    log:
      category:
        "io.quarkus.mongodb.panache.common.runtime":
          min-level: TRACE
          level: DEBUG
        "org.mongodb":
          min-level: TRACE
          level: DEBUG
"%debug-oidc":
  quarkus:
    log:
      category:
        "io.quarkus.oidc":
          min-level: TRACE
          level: TRACE
"%debug-camel":
  quarkus:
    log:
      category:
        "org.apache.camel":
          min-level: TRACE
          level: DEBUG
"%debug-all":
  quarkus:
    log:
      min-level: TRACE
      level: DEBUG
"%trace-all":
  quarkus:
    log:
      min-level: TRACE
      level: TRACE
