###############################################################################
# DEV PROFILES
###############################################################################
"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy.reactive":
          level: DEBUG
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536
"%debug-mongodb":
  quarkus:
    log:
      category:
        "io.quarkus.mongodb.panache.common.runtime":
          level: DEBUG
        "org.mongodb":
          level: DEBUG
"%debug-oidc":
  quarkus:
    log:
      category:
        "io.quarkus.oidc":
          level: TRACE
"%debug-camel":
  quarkus:
    log:
      category:
        "org.apache.camel":
          level: DEBUG
"%trace":
  quarkus:
    log:
      category:
        esthesis:
          level: TRACE
"%trace-all":
  quarkus:
    log:
      level: TRACE
