quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    level: WARN
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
  mongodb:
    connection-string: mongodb://esthesis:esthesis@localhost:27017/esthesis

  rest-client:
    logging:
      scope: request-response
      body-limit: 4096
    RegistryResource:
      url: http://localhost:59030
      scope: Singleton
    CryptoResource:
      url: http://localhost:59040
      scope: Singleton
    TagResource:
      url: http://localhost:59020
      scope: Singleton

kafka:
  bootstrap:
    servers:
      - localhost:9092
