quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
  mongodb:
    connection-string: mongodb://esthesis-dev-mongo-1:27017,esthesis-dev-mongo-2:27017
  opentelemetry:
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317

  rest-client:
    RegistryResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
    CryptoResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
    TagResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs

kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094
