quarkus:
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: esthesis-dev-loki-gelf-udp
        port: 12201
        include-full-mdc: true
  mongodb:
    connection-string: mongodb://esthesis-dev-mongodb-0:27017,esthesis-dev-mongodb-1:27017
  opentelemetry:
    enabled: true
    tracer:
      exporter:
        otlp:
          endpoint: http://esthesis-dev-jaeger-collector:4317

  rest-client:
    RegistryResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
    CAResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
    TagResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton
    DataflowResource:
      url: http://esthesis-dev-apisix-gateway/dev
      scope: Singleton

mp:
  jwt:
    verify:
      publickey:
        location: http://esthesis-dev-keycloak/realms/esthesis/protocol/openid-connect/certs

kafka:
  bootstrap:
    servers:
      - esthesis-dev-kafka:9094
