quarkus:
  container-image:
    group: esthesisiot
    name: esthesis-srv-device
  mongodb:
    connection-string: mongodb://esthesis:esthesis@mongodb:27017/esthesis
    database: esthesis
  devservices:
    enabled: false
mp:
  jwt:
    verify:
      publickey:
        location: "http://192.168.21.2/realms/esthesis/protocol/openid-connect/certs"
