quarkus:
  application:
    name: esthesis-srv-command
  container-image:
    group: esthesisiot
    name: esthesis-srv-command
  mongodb:
    connection-string: mongodb://mongodb:27017
    database: esthesis
    credentials:
      username: esthesis
      password: esthesis
  devservices:
    enabled: false
  log:
    level: warn
    category:
      esthesis:
        level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  banner:
    enabled: false
  opentelemetry:
    enabled: false
  index-dependency:
    avro:
      group-id: org.apache.avro
      artifact-id: avro

mp:
  jwt:
    verify:
      publickey:
        location: "http://esthesis-keycloak/realms/esthesis/protocol/openid-connect/certs"
  messaging:
    outgoing:
      esthesis-command-request:
        value:
          serializer: esthesis.service.command.impl.serialization.EsthesisCommandRequestMessageSerializer
