quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: false
        host: "localhost"
        port: 12201
  mongodb:
    database: esthesiscore
    credentials:
      username: esthesis-system
      password: esthesis-system
  otel:
    sdk:
      disabled: true
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://grafana-tempo-distributor.esthesis:4317
  config:
    locations: "../../../../_dev/profiles"
  rest-client:
    # A self-reference to be able to use the Audited annotation.
    AuditResource:
      url: http://localhost:59140
      scope: Singleton
