quarkus:
  log:
    level: ERROR
  devservices:
    enabled: true
    timeout: 5m
  mongodb:
    database: esthesiscore-test
    devservices:
      image-name: "mongo:4.4.6"
  http:
    test-port: 0

