quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    min-level: TRACE
    category:
      esthesis:
        level: DEBUG
    handler:
      gelf:
        enabled: true
        host: "gelf-ingester.esthesis.localdev"
        port: 12201
        include-full-mdc: true
        skip-hostname-resolution: true
  otel:
    traces:
      sampler: always_on
    exporter:
      otlp:
        traces:
          endpoint: http://otel-ingester.esthesis.localdev:4317
  config:
    locations: "../../../../_dev/profiles"

esthesis:
  oidc:
    authority: "http://keycloak.esthesis.localdev/realms/esthesis"
    redirect-url: "http://localhost:4200/callback"
    post-logout-redirect-uri: "http://localhost:4200/logged-out"
